### PR TITLE
fixes fixed fixed

### PR DESCRIPTION
**Pull request by minamouse**

### CODE REVIEW

**Comment by bsansouci** [comment]
Mmmh do you mind changing your tab sizes to 2 spaces and not 14? :p

**Comment by Schmavery** [comment]
I do take credit for also already having advised this course of action.

**Comment by Schmavery** [comment]
@bsansouci How do you feel about it now?  Tabs have been converted back to spaces.

**Comment by markhughes** [comment]
You should use tabs, then change the tab display size in your editor. 

That way everyone can use whatever spacing they prefer. :)

**Comment by Schmavery** [comment]
A couple of schools of thought on this.
http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml#Code_formatting
http://code.google.com/p/gmaps-utility-library-dev/wiki/JavascriptCodingConventions
http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e

I'm not saying that our code is pretty (especially in this project), just that in the absence of a hard standard, consistency is best :D
Not much point in quibbling over holy wars.

**Pull request merged**
